### ISSUE TITLE
Make failed

### ISSUE THREAD

**Issue by thwaller** [iBroadcastMediaServices/MediaSyncLiteLinux#1]
Make fails on Ubuntu 18.04. I also needed to add libssl-dev, which is not mentioned in the install directions. Given this, maybe there is something else missing that is required? I have seen a few others mention such an issue on unrelated installs, and there have been a few working suggestions all involving the command lines used and the order of things and some calling for "-lssl" to be added, etc.

$ make
make[1]: Entering directory '/home/xxxxxx/devel/source/MediaSyncLiteLinux-master/src'
directories  requested
if [ ! -d .. ] ; then mkdir .. ; fi;
directories done
../mediasynclite  requested
cc tools.o ibmsl.o -o ../mediasynclite `pkg-config --libs gtk+-3.0 libcurl libssl` -ljansson -lpthread -rdynamic
/usr/bin/x86_64-linux-gnu-ld: tools.o: undefined reference to symbol 'MD5@@OPENSSL_1_1_0'
//usr/lib/x86_64-linux-gnu/libcrypto.so.1.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:27: recipe for target '../mediasynclite' failed
make[1]: *** [../mediasynclite] Error 1
make[1]: Leaving directory '/home/xxxxxx/devel/source/MediaSyncLiteLinux-master/src'
Makefile:8: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by flagoworld** [comment]
Hi thwaller,

The error says `undefined reference to symbol 'MD5@@OPENSSL_1_1_0'` which sounds like you might not have OpenSSL 1.1 installed. Could you verify whether or not it is installed and let me know? Make sure that both `openssl` and `openssl-devel` are installed.

Thanks

**Comment by thwaller** [comment]
openssl 1.1.0g-2ubuntu4 is installed.
openssl-devel does not exist, at least for Ubuntu.  If it is suitable, libssl-dev 1.1.0g-2ubuntu4 is installed.
I have gone through the dependencies listed in the readme.md file.

**Comment by flagoworld** [comment]
You are right, `openssl-devel` does not exist and the correct library is `libssl-dev`, which you have installed.

Can you try running `sudo ldconfig` first and see if that works?

**Comment by thwaller** [comment]
same result

**Comment by flagoworld** [comment]
Hi thwaller,

I was able to reproduce the issue. I have made a change to the src/Makefile that allows it to build per the readme.

**Comment by thwaller** [comment]
I applied the change and can confirm that it works.
