### ISSUE TITLE
Debian package

### ISSUE THREAD

**Issue by alabarre** [iBroadcastMediaServices/MediaSyncLiteLinux#10]
The program is easy enough to compile and install on Debian, but are there plans to release an official .deb package and possibly an apt repository, at least for the latest stable version?

**Comment by flagoworld** [comment]
At the moment there are no plans to do this.

**Comment by flagoworld** [comment]
Hi @alabarre, 

Thanks for the great idea! This is something we plan to do, but we do not currently have a time frame when it will get done. If you are interested in contributing to this, we would welcome that!

**Comment by gilphilbert** [comment]
I've opened a pull request with the information needed to package your releases as debian packages: #12

**Comment by flagoworld** [comment]
Great! I will take a look at it and get it merged in.
