### ISSUE TITLE
Doesn't Work in Linux. Can't install it.

### ISSUE THREAD

**Issue by ghost** [iBroadcastMediaServices/MediaSyncLiteLinux#14]
Why not just make a  deb or flatpak? Especially in this day an age...
make[1]: Entering directory '/home/***********/Applications/MediaSyncLiteLinux-master/src'
directories  requested
if [ ! -d .. ] ; then mkdir .. ; fi;
directories done
cc -Wall -Wextra -Wundef -Wshadow -Wpointer-arith -Wbad-function-cast -Wcast-align -Wwrite-strings -Wredundant-decls -Wformat-nonliteral -Wnested-externs -pedantic -std=gnu99 -O3 -pthread -D_REENTERANT `pkg-config --cflags gtk+-3.0 libcurl libssl libcrypto` -c ../src/tools.c -o tools.o
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
Package libcurl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcurl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcurl' found
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libssl' found
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
../src/tools.c:31:10: fatal error: openssl/md5.h: No such file or directory
   31 | #include <openssl/md5.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:38: tools.o] Error 1
make[1]: Leaving directory '/home/***********/Applications/MediaSyncLiteLinux-master/src'
make: *** [Makefile:12: all] Error 2

**Comment by flagoworld** [comment]
Did you see that there is a deb file in the releases section? Could you try that and see if it works?

https://github.com/iBroadcastMediaServices/MediaSyncLiteLinux/releases
