### ISSUE TITLE
No package 'libcurl' found .

### ISSUE THREAD

**Issue by saadrehman** [iBroadcastMediaServices/MediaSyncLiteLinux#15]
The READ says to use 
libcurl
    - on Ubuntu, use libcurl4-openssl-dev

But how? Where do I specify? i am on Ubuntu, but running make is giving me this error.

**Comment by flagoworld** [comment]
You should just be able to install it using apt:

`sudo apt install libcurl4-openssl-dev`

Let me know if that doesn't work for you. Be sure to include the build log so I can see the error directly.
