### ISSUE TITLE
*** stack smashing detected ***: <unknown> terminated - Aborted (core dumped)

### ISSUE THREAD

**Issue by sks316** [iBroadcastMediaServices/MediaSyncLiteLinux#2]
Tried to upload music today, but was greeted with an error upon signing in.
I use Ubuntu 18.04 LTS if it matters.
The error:
*** stack smashing detected ***: <unknown> terminated
Aborted (core dumped)

**Comment by sks316** [comment]
Hello? Does anyone even maintain this anymore?

**Comment by Rodster001** [comment]
Hello. Can you please email us at support@ibroadcast.com so we can help you from there?

**Comment by sks316** [comment]
Done, I'll wait on a response.

**Comment by dionearle** [comment]
I'm also having the same issue, would be great to have a solution as I currently have no way of uploading my library from my Linux machine

**Comment by flagoworld** [comment]
Hi, I have just committed a change to the code that should resolve this issue. Give it a try and let me know.

**Comment by dmoebius** [comment]
Alternatively, if you are a little familiar with Java, you can try my Java uploader, which is derived from the original iBroadcast Java uploader example:
https://github.com/dmoebius/ibroadcast-java-uploader

**Comment by sks316** [comment]
Thanks, looks like it works now! It's worth noting that there seem to be a lot of grammatical errors.

**Comment by flagoworld** [comment]
Excellent! Thanks for the heads up on the grammatical errors. We will take a look at that when we can.
