### ISSUE TITLE
Does not run in Linux Mint 21.3

### ISSUE THREAD

**Issue by PiperKev** [iBroadcastMediaServices/MediaSyncLiteLinux#21]
After installing the .deb, I ran "mediasynclite" and got the following error:

mediasynclite: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory.

**Comment by PiperKev** [comment]
I was able to download an old version of libcrypto.so.1.1 via pkgs.org (https://pkgs.org/search/?q=libcrypto.so.1.1), and that worked.

**Comment by erseco** [comment]
The error also occurs on ubuntu server

**Comment by illtellyoulater** [comment]
@flagoworld
@tobz619
@gilphilbert
@Rodster001
@schw1804

what about fixing this?

**Comment by gilphilbert** [comment]
The package needs to be built against a later version of Debian as libcrypto has been updated in newer releases.

I don't work for iBroadcast and I don't have any permissions on this repo so there's nothing I can do. I don't know if the iBroadcast team still maintain this package or not, hopefully they can compile for a modern version of Debian and issue a new release.

In the meantime, you can still use the manual method to clone the repo and compile it locally. It's a simple build and, if you follow the instructions, should be quick.

**Comment by gilphilbert** [comment]
> I was able to download an old version of libcrypto.so.1.1 via pkgs.org (https://pkgs.org/search/?q=libcrypto.so.1.1), and that worked.

I don't recommended this; adding random objects to your distro can do bad things and if libcrypto has been updated then adding an old version (that won't be updated) could result in security vulnerabilities on your machine.
