### ISSUE TITLE
No license provided.

### ISSUE THREAD

**Issue by ric2b** [iBroadcastMediaServices/MediaSyncLiteLinux#4]
I would like to modify/contribute to the project but without a license I can't.

Do you plan on licensing the project as FOSS?

Thank you :)

**Comment by ric2b** [comment]
Hey @flagoworld and @Rodster001,

sorry to bother you, but since it's been 2 weeks I thought of adding a mention just in case you don't check this repo often.

I'd like to help make it easier to install for other people :)

**Comment by flagoworld** [comment]
Hi @ric2b,

Sorry for the long delay in responding. Next week we will update the repo with a license. I will respond here once that is done.

Thanks!

**Comment by ric2b** [comment]
Hey @flagoworld / @Rodster001 , any news about this?

**Comment by flagoworld** [comment]
Hi @ric2b, the license has been added.
