### ISSUE TITLE
Problem executing ibroadcast-uploader.py

### ISSUE THREAD

**Issue by lbr38** [iBroadcastMediaServices/MediaSyncLiteLinux#8]
Hi

I know this is the github for MediaSync but I can't find help from your email support. I have an issue with the python script ibroadcast-uploader.py.

I installed the two required modules 'glob' and 'requests' but I still have an error when I try to execute the script : 

```
root@xu4:~/scripts# pip3.6 install glob3
Requirement already satisfied: glob3 in /usr/local/lib/python3.6/dist-packages (0.0.1)
root@xu4:~/scripts# pip3.6 install requests
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (2.24.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3/dist-packages (from requests) (1.22)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/lib/python3/dist-packages (from requests) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3/dist-packages (from requests) (2.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests) (2018.1.18)
root@xu4:~/scripts# python3.6 ibroadcast-uploader.py email password
  File "ibroadcast-uploader.py", line 40
    except ValueError, e:
                     ^
SyntaxError: invalid syntax
```

Maybe I am wrong with the modules installed ? Or with the python version ? 

I'm very new to python and I don't understand that syntax error..

Thank you for your help!

**Comment by flagoworld** [comment]
Hi @lbr38,

If you have any questions such as this in the future, you can contact support by logging into your iBroadcast account, opening the side menu, and clicking the "Feedback & Support" button.

That said, the issue you are experiencing is because you are trying to run the script using Python 3. This script requires that you use Python 2.7.

Let me know if that does not resolve.

**Comment by lbr38** [comment]
Hi @flagoworld 

Thank you for your help!

The official documentation says **ibroadcast-uploader.py Python 3 port. Requires requests and glob, available via the Python package manager (pip)**.
Link to the said documentation : https://project.ibroadcast.com/

This is why I tried to execute it using Python 3!

Can you confirm me which version I should use? And considering python2.7 is no longer maintened, could the script be ported for python 3 (if not already the case)?

Thank you again for your time

**Comment by flagoworld** [comment]
Good point. I will update the script to work with python 3. I’ll write here when it’s updated.

**Comment by lbr38** [comment]
@flagoworld Thank you!! :)

**Comment by flagoworld** [comment]
You are welcome!

The script is now fixed. You can re-download from https://project.ibroadcast.com

**Comment by lbr38** [comment]
Thank you @flagoworld for this update, very reactive!

If I may have one or two more suggestions, I would be nice to have an option to make the script fully automatic without human intervention. The prompt asking to list or upload actually makes it difficult.

I tried the following:
`echo U | ibroadcast-uploader.py <login> <password>`
Which works in a terminal but when launched from a bash script it don't (still asking for an answer) and seems to hang (i have to kill the process).

Also, the possibility to specify a directory to upload could be nice too, for exemple: 
`ibroadcast-uploader.py <login> <password> /forderpath/*.mp3`

Sorry, I know I may asking much and this is no imperative, but I (as many others I guess) am coming from Google Music and I was using python's gmusicapi-scripts to automatically upload the music. I think the features I suggest will soon be asked by others people aswell, because iBroadcast is now, for many of us, the answer to GMusic closing!

Or maybe you could consider make a new repo here for ibroadcast-uploader.py and let contributors add new features? I am no good at python so I would not but I know some people could easily make the features above.

Thank you again for your time, I hope you understand me, english is not my mother tongue.

Regards

Ludovic

**Comment by flagoworld** [comment]
Thanks for the great suggestions, @lbr38. At this time we won't be adding additional features to these scripts, however we are strongly considering putting them all in a git repo so you and others may contribute these great ideas in the future! I will let you know as soon as there is an update on the repository idea.

Keep in mind that these are just scripts, so if you are so inclined you can edit them yourself. For example, comment out the lines that ask for user input and hardcode user input into the variables. Then the script would assume you are telling it to begin uploading and do so.

**Comment by lbr38** [comment]
Ok I found how to hardcode the user input as you suggested, thank you!
